In [1]:
import wandb

In [2]:
from neurobench.datasets.primate_reaching import PrimateReaching

In [3]:
PrimateReaching.md5s.keys()

dict_keys(['indy_20170131_02.mat', 'indy_20160630_01.mat', 'indy_20160622_01.mat', 'loco_20170301_05.mat', 'loco_20170215_02.mat', 'loco_20170210_03.mat'])

In [4]:
md5 = PrimateReaching.md5s['indy_20170131_02.mat']
print(md5)

2790b1c869564afaa7772dbf9e42d784


In [6]:
import os
print(os.path.dirname(md5))

In [18]:
dataset = PrimateReaching(
    file_path='../data/datasets',
    filename='indy_20160407_02.mat',
    num_steps=1,
    download=True,
    train_ratio=0.5,
    remove_segments_inactive=True
)

KeyError: 'indy_20160407_02.mat'

In [15]:
import numpy as np

np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [3]:
test_dataset = PrimateReaching(
    file_path='../data/datasets',
    filename='indy_20170131_02.mat',
    num_steps=1,
    download=True,
    train_ratio=0.5,
    remove_segments_inactive=False
)

Loading indy_20170131_02.mat


In [4]:
len(test_dataset[0][0][0])

96

torch.Size([96])

In [ ]:
dataset

In [4]:
len(dataset)

203995

In [6]:
len(dataset[0][0][0])

96

In [7]:
dataset[0]

(tensor([[0., 2., 0., 0., 0., 0., 4., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 2., 0.,
          2., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
          1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 1., 0., 0.]]),
 tensor([-0.1457, -0.1481]))

In [8]:
dataset.split_data()

In [9]:
len(dataset)

407990

In [10]:
len(dataset.ind_train)

200868

In [11]:
len(dataset.ind_test)

104232

In [12]:
dataset[0]

(tensor([[0., 2., 0., 0., 0., 0., 4., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 2., 0.,
          2., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
          1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 1., 0., 0.]]),
 tensor([-0.1457, -0.1481]))

In [13]:
ind_train_val = dataset.ind_train + dataset.ind_val
len(ind_train_val)

303758

In [14]:
import math

eff_ratio_val = 0.25 / (math.ceil(len(ind_train_val) / len(dataset)*100) / 100)
eff_ratio_val

0.3333333333333333

In [15]:
import numpy as np

n_val = int(np.round(len(dataset) * eff_ratio_val))
n_val

135997

In [16]:
array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
start_idx = np.random.choice(a=array[:-3], size=1)[0]
start_idx

5

In [17]:
ind_train_val[:-n_val]

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [18]:
start_idx = np.random.choice(a=ind_train_val[:-n_val], size=1)[0]
start_idx

19849

In [19]:
ind_val = np.array(ind_train_val[start_idx:start_idx + n_val])
ind_val

array([19849, 19850, 19851, ..., 55409, 55410, 55411])

In [20]:

ind_train = np.array(sorted(set(ind_train_val) - set(ind_val)))
ind_train

array([100434, 100435, 100436, ..., 151876, 151877, 151878])

In [21]:
similar_train_val = np.intersect1d(ind_val, ind_train)
similar_train_val

array([], dtype=int64)

In [22]:
similar_train_test = np.intersect1d(ind_train_val, test_dataset.ind_test)
similar_train_test

array([], dtype=int64)

In [23]:
len(dataset.ind_val)

102890

In [24]:
dataset.labels.T

tensor([[-0.1457, -0.1481],
        [-0.1421, -0.1479],
        [-0.1347, -0.1474],
        ...,
        [-0.1401,  0.1501],
        [-0.1251,  0.1346],
        [-0.1168,  0.1259]])

In [25]:
spikes_train = dataset.samples.T[ind_train]

In [26]:
spikes_train

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [4]:
import logging
import sys
import colorlog

def get_logger(name=None):
    logger = colorlog.getLogger(name or "rsnn")

    if logger.hasHandlers():
        logger.handlers.clear()

    logger.setLevel(logging.INFO)
    handler = colorlog.StreamHandler(stream=sys.stdout)

    formatter = colorlog.ColoredFormatter(
        '%(asctime_log_color)s[%(asctime)s] '
        '%(levelname_log_color)s[%(levelname)s] '
        '%(name_log_color)s[%(name)s] '
        '%(message_log_color)s- %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S',
        log_colors={
            'DEBUG': 'cyan',
            'INFO': 'green',
            'WARNING': 'yellow',
            'ERROR': 'red',
            'CRITICAL': 'red,bg_white',
        },
        secondary_log_colors={
            'asctime': {
                'DEBUG': 'white',
                'INFO': 'blue',
                'WARNING': 'yellow',
                'ERROR': 'red',
                'CRITICAL': 'red,bg_white',
            },
            'levelname': {
                'DEBUG': 'white',
                'INFO': 'yellow',
                'WARNING': 'blue',
                'ERROR': 'red',
                'CRITICAL': 'red,bg_white',
            },
            'name': {
                'DEBUG': 'white',
                'INFO': 'green',
                'WARNING': 'yellow',
                'ERROR': 'red',
                'CRITICAL': 'red,bg_white',
            },
            'message': {
                'DEBUG': 'green',
                'INFO': 'white',
                'WARNING': 'yellow',
                'ERROR': 'red',
                'CRITICAL': 'red,bg_white',
            },
        },
        style='%'
    )

    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.propagate = False

    return logger


In [57]:
logger = get_logger('rsnn')

In [58]:
logger.info('This is an info message')

[2025-04-30 10:47:22] [INFO] [rsnn] - This is an info message


In [13]:
import pprint

def formatted_cfg_logger(cfg):
    """
    Log the configuration in a formatted way.
    """
    formatted_cfg = pprint.pformat(cfg, indent=2, compact=False, depth=1)
    # print(formatted_cfg)
    # formatted_cfg = "{\n" + "\n".join(f'{line}' for line in formatted_cfg[1:-1]) + "\n}"

    return formatted_cfg

In [3]:
config = {'filename': 'indy_20170131_02.mat', 'file_path': '/home/cc/efficient-rsnn-bmi/data/datasets', 'train_ratio': 0.8, 'val_ratio': 0.1, 'random_val': False, 'stride': 0.004, 'extend_data': True, 'sample_duration': 2.0, 'remove_segments_inactive': False, 'p_drop': 0.0, 'p_insert': 0.0, 'jitter_sigma': 0.0}

In [5]:
logger = get_logger('rsnn')

In [14]:
formatted_cfg = formatted_cfg_logger(config)
logger.info(formatted_cfg)

[2025-05-06 09:44:29] [INFO] [rsnn] - { 'extend_data': True,
  'file_path': '/home/cc/efficient-rsnn-bmi/data/datasets',
  'filename': 'indy_20170131_02.mat',
  'jitter_sigma': 0.0,
  'p_drop': 0.0,
  'p_insert': 0.0,
  'random_val': False,
  'remove_segments_inactive': False,
  'sample_duration': 2.0,
  'stride': 0.004,
  'train_ratio': 0.8,
  'val_ratio': 0.1}


In [24]:
formatted_cfg.splitlines()

['{',
 '',
 " 'extend_data': True,",
 "  'file_path': '/home/cc/efficient-rsnn-bmi/data/datasets',",
 "  'filename': 'indy_20170131_02.mat',",
 "  'jitter_sigma': 0.0,",
 "  'p_drop': 0.0,",
 "  'p_insert': 0.0,",
 "  'random_val': False,",
 "  'remove_segments_inactive': False,",
 "  'sample_duration': 2.0,",
 "  'stride': 0.004,",
 "  'train_ratio': 0.8,",
 "  'val_ratio': 0.1",
 '',
 '}']

In [3]:
!pip show stork


Name: stork
Version: 3.2.1
Summary: Update libraries on Databricks
Home-page: https://github.com/shoprunner/stork
Author: Hanna Torrence
Author-email: data-science@shoprunner.com
License: BSD-3-Clause
Location: /home/cc/efficient-rsnn-bmi/venvs/efficient-rsnn-bmi/lib/python3.12/site-packages
Requires: click, click-log, configparser, requests, simplejson
Required-by: efficient-rsnn-bmi


In [2]:
!pip install seaborn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 61.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 107.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 72.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 108.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 108.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/11 [seaborn]0/11 [seaborn]ib]


In [3]:
from stork.models import RecurrentSpikingModel

In [10]:
import __main__
print(__main__.__package__)

None


In [13]:
import sys
import os

sys.path.append(os.path.abspath("..")) 

In [17]:
int(2 / 0.004)

500

In [18]:
from efficient_rsnn_bmi.experiments.models.rsnn.rsnn import BaselineRecurrentSpikingModel

model = BaselineRecurrentSpikingModel(
    250,
    nb_time_steps=500,
    nb_inputs=192,
    dtype='float32'
)

In [19]:
model

BaselineRecurrentSpikingModel()

In [90]:
import torch
# import the dataloader
from torch.utils.data import DataLoader

# import the dataset, preprocessors and postprocessors you want to use
from neurobench.datasets import SpeechCommands
from neurobench.processors.preprocessors import S2SPreProcessor
from neurobench.processors.postprocessors import ChooseMaxCount

# import the NeuroBench wrapper to wrap the snnTorch model
from neurobench.models import SNNTorchModel

# import metrics
from neurobench.metrics.workload import (
    ActivationSparsity,
    SynapticOperations,
    ClassificationAccuracy,
    R2,
)
from neurobench.metrics.static import (
    Footprint,
    ConnectionSparsity,
)

# import the benchmark class
from neurobench.benchmarks import Benchmark

In [91]:
from torch import nn
import snntorch as snn
from snntorch import surrogate

beta = 0.9
spike_grad = surrogate.fast_sigmoid()
net = nn.Sequential(
    nn.Flatten(),
    nn.Linear(20, 256),
    snn.Leaky(beta=beta, spike_grad=spike_grad, init_hidden=True),
    nn.Linear(256, 256),
    snn.Leaky(beta=beta, spike_grad=spike_grad, init_hidden=True),
    nn.Linear(256, 256),
    snn.Leaky(beta=beta, spike_grad=spike_grad, init_hidden=True),
    nn.Linear(256, 35),
    snn.Leaky(beta=beta, spike_grad=spike_grad, init_hidden=True, output=True),
)

In [104]:
!nvidia-smi

2570.71s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


Mon May 19 12:21:22 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.230.02             Driver Version: 535.230.02   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P100-SXM2-16GB           Off | 00000000:04:00.0 Off |                    0 |
| N/A   35C    P0              43W / 300W |   2422MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [97]:
def to_cuda(batch):
    inputs, targets = zip(*batch)  # unzip list of tuples
    inputs = torch.stack(inputs).to('cuda')
    targets = torch.tensor(targets).to('cuda')
    return inputs, targets

In [98]:
test_set = SpeechCommands(path="data/speech_commands/", subset="testing")

test_set_loader = DataLoader(test_set, batch_size=500, shuffle=True, collate_fn=to_cuda)


In [99]:
net.load_state_dict(torch.load("s2s_gsc_snntorch"))

net.to("cuda")

# Wrap our net in the SNNTorchModel wrapper
model = SNNTorchModel(net)

In [100]:
preprocessors = [S2SPreProcessor(device='cuda')]
postprocessors = [ChooseMaxCount()]

In [113]:
static_metrics = [Footprint, ConnectionSparsity]
workload_metrics = [R2]

In [114]:
benchmark = Benchmark(model, test_set_loader,
                      preprocessors, postprocessors, [static_metrics, workload_metrics])

In [115]:
results = benchmark.run()
print(results)

Running benchmark


  4%|▍         | 1/23 [00:00<00:13,  1.66it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


  9%|▊         | 2/23 [00:01<00:12,  1.67it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 13%|█▎        | 3/23 [00:01<00:11,  1.67it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 17%|█▋        | 4/23 [00:02<00:11,  1.68it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 22%|██▏       | 5/23 [00:02<00:10,  1.68it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 26%|██▌       | 6/23 [00:03<00:10,  1.68it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 30%|███       | 7/23 [00:04<00:10,  1.56it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 35%|███▍      | 8/23 [00:05<00:09,  1.50it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 39%|███▉      | 9/23 [00:05<00:09,  1.46it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 43%|████▎     | 10/23 [00:06<00:09,  1.43it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 48%|████▊     | 11/23 [00:07<00:08,  1.42it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 52%|█████▏    | 12/23 [00:07<00:07,  1.40it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 57%|█████▋    | 13/23 [00:08<00:07,  1.40it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 61%|██████    | 14/23 [00:09<00:06,  1.39it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 65%|██████▌   | 15/23 [00:10<00:05,  1.39it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 70%|██████▉   | 16/23 [00:10<00:05,  1.38it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 74%|███████▍  | 17/23 [00:11<00:04,  1.38it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 78%|███████▊  | 18/23 [00:12<00:03,  1.38it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 83%|████████▎ | 19/23 [00:13<00:02,  1.38it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 87%|████████▋ | 20/23 [00:13<00:02,  1.38it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 91%|█████████▏| 21/23 [00:14<00:01,  1.38it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


 96%|█████████▌| 22/23 [00:15<00:00,  1.38it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1


100%|██████████| 23/23 [00:15<00:00,  1.46it/s]

Error running workload metric 'R2': too many indices for tensor of dimension 1
{'Footprint': 599960, 'ConnectionSparsity': 0.0, 'R2': 0.0}
